### ISSUE TITLE
Understat - stats per player, per match

### ISSUE THREAD

**Issue by luistelmocosta** [slehkyi/notebooks-for-articles#2]
Hello, have you ever consider doing what you did, for each team but for every player throughout all those seasons?

I am trying to do it but I am having an hard time due to the pagination of the table. Any chance you can help me with a quick example for just one player?

Kind regards and thank you for your work!

**Comment by slehkyi** [comment]
I have already had some requests regarding the player data - will try to find some time and scrape that data too.

Meanwhile, if you're having problems with pagination, try to find REST calls and get the data using them. When I was collecting data for the teams I didn't think about it, but this method might be much easier.

Cheers!
